### ISSUE TITLE
No data or chart options shown when querying Timescale

### ISSUE THREAD

**Issue by lastditchusername** [KensoBI/spc-chart#57]
I'm unable to get the SPC chart to show anything with our data. 
Notes from troubleshooting and checking other issues for solutions:
- The Grafana random walk query does render as expected
- Query is in "Table" format
- Time is detected as a regular timestamp
- Dashboard crashes when any of "Feature", "Nominal", or "Control" are not present in query
  ![image](https://github.com/user-attachments/assets/db415534-2be1-4383-9f2f-1c84e7705bc7)

- Query does return data when "Table View" is selected
  ![image](https://github.com/user-attachments/assets/674972be-2648-40cc-a15f-2e067b9c3afb)

- If "Control" is set to 0, no chart is displayed at all, and Constants cannot be added to the chart
  
  ![image](https://github.com/user-attachments/assets/ac83a094-cc09-4177-a845-4c0fdbd1cd96)
  - If "Control" is set to anything else, a "No Data" error is shown in the chart area, and value can be selected as a constant
  
  ![image](https://github.com/user-attachments/assets/4f497a4e-723b-47ef-9593-9c94b124ce83)

Query being used is as below:

```
SELECT
  CAST(measured_value AS FLOAT) as value,
  time,
  parameter_name as "Feature",
  target as "Nominal",
  upper_bound,
  lower_bound,
  0 as "Control"
FROM xx_database_xx
WHERE ( [variables] ) 
AND $__timeFilter("time")
```

**Comment by mrtomeq** [comment]
By the way, version 2 of the plugin is currently under review by Grafana and will be released in the coming days. It is a complete rewrite with a new and improved editor.

Our documentation has already been updated: https://docs.kensobi.com/panels/spc-chart/spc

While we wait for it to be published in the Grafana plugin repository, you can install it manually from  https://github.com/KensoBI/spc-chart/releases/tag/2.0.1 

![image](https://github.com/user-attachments/assets/f30922fe-7acd-4ba2-b3c0-73bb597cc096)

**Comment by mrtomeq** [comment]
V2 has been published. Please check and create new issue if this problem persists.
